### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by AbdelrahmanAA** [iist-sysnet/UDTNSim#1]
I am trying to run main file but i got this problem 
does any one know how to solve it 
![image](https://user-images.githubusercontent.com/16548842/38147881-fbd93876-3408-11e8-9578-c0d25f35199a.png)

**Comment by 4sarathbabu** [comment]
Dear abdoelzamalkawy,

The error denotes that there does not exist any junction to initially position mobile objects on the map, i.e., the list named 'nodes' is empty, on which the function choice() failedd. I presume that there exists a mismatch between mobile objects and map. Whether you changed the map file to any other city?

Sarath Babu

**Comment by AbdelrahmanAA** [comment]
no i didn't change any thing
i just typed python main.py in console
and this happened

so i tried to fix it and i solved it
by modifying some files

so it worked for me now

**Comment by 4sarathbabu** [comment]
Oh. That's great. If you can share the problem and the solution, it will be more helpful to us and other users. 

Thanks for using the simulator.
Sarath Babu

**Comment by AbdelrahmanAA** [comment]
how can i share my solution

**Comment by 4sarathbabu** [comment]
I wish you to mention the modifications that are made to execute the code successfully. When I run the code in my Linux machine, it was working fine. Since you execute the code in Windows, I doubt whether the problem is due to the operating system and corresponding Python libraries. :)

Thanks 
Sarath Babu

**Comment by AbdelrahmanAA** [comment]
in initisim.py

event_interval_list = numpy.random.exponential(int(event_interval), int
(no_of_event_points))
instead of
event_interval_list = numpy.random.exponential(event_interval,
no_of_event_points)


in stationary.py

initial_node = random.choice(nodes.keys())
instead of
initial_node = random.choice(nodes)


in pathtype.py

initial_node = random.choice(nodes.keys())
instead of
initial_node = random.choice(nodes)


now i need to know how should i use this simulator :D :D

**Comment by 4sarathbabu** [comment]
Thanks you very much for your explanation. :) :) 

Developing new mobility models and data handoff patterns for mobile objects is described in detail in the following document:
https://arxiv.org/pdf/1709.05645.pdf

Sarath Babu
