### ISSUE TITLE
Using different maps

### ISSUE THREAD

**Issue by eqfarhad** [iist-sysnet/UDTNSim#2]
Dear Sarath Babu,

first, thank you for sharing this code. I recently begin working on DTN networks and find your code really helpful.

There is only a tiny problem, when we want to change the map and use another location osm file, we will get the following error:

![1](https://user-images.githubusercontent.com/56564631/73122601-2315fd80-3f87-11ea-969e-d2294896f688.PNG)

right now it's working well with Manhattan or Dharavi osm files but even if I change it to London which is available in the map folder right now, I come up with the above error.

Good news is that I found the problem+solution and will create a pull request for it :)

Best Regards,
Farhad

**Comment by 4sarathbabu** [comment]
Dear Farhad,

Thank you very much for your interest in our UDTNSim simulator. It is great that you found out the solution for the problem that you encountered. Always welcome your suggestions in future as well. 

Regards
Sarath Babu
